In [3]:
import pandas as pd
import numpy as np

In [4]:
df=pd.read_csv("preprocessed_data.csv")

In [5]:
df

movie_id                                     title  \
0        19995                                    Avatar   
1          285  Pirates of the Caribbean: At World's End   
2       206647                                   Spectre   
3        49026                     The Dark Knight Rises   
4        49529                               John Carter   
...        ...                                       ...   
4801      9367                               El Mariachi   
4802     72766                                 Newlyweds   
4803    231617                 Signed, Sealed, Delivered   
4804    126186                          Shanghai Calling   
4805     25975                         My Date with Drew   

                                                   tags  
0     in the 22nd century, a paraplegic marine is di...  
1     captain barbossa, long believed to be dead, ha...  
2     a cryptic message from bond’s past sends him o...  
3     following the death of district attorney harve...  
4     john carter is a war-weary, former military ca...  
...                                                 ...  
4801  el mariachi just wants to play his guitar and ...  
4802  a newlywed couple's honeymoon is upended by th...  
4803  "signed, sealed, delivered" introduces a dedic...  
4804  when ambitious new york attorney sam is sent t...  
4805  ever since the second grade when he first saw ...  

[4806 rows x 3 columns]

In [6]:
from sklearn.feature_extraction.text import CountVectorizer

In [7]:
cv=CountVectorizer(stop_words='english',max_features=3500)

In [8]:
cv.fit_transform(df["tags"]).toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [9]:
cv.get_feature_names_out()[1:200]

array(['10', '11', '12', '13', '14', '15', '16', '17', '18', '18th', '19',
       '1930s', '1940s', '1950s', '1960s', '1970s', '1980s', '19th',
       '19thcentury', '20', '20th', '24', '25', '30', '3d', '40', '50',
       'aaron', 'aaroneckhart', 'abandoned', 'abducted', 'ability',
       'able', 'abuse', 'abusive', 'academy', 'accept', 'accepts',
       'access', 'accident', 'accidentally', 'accompanied', 'account',
       'accused', 'act', 'action', 'actions', 'activist', 'activities',
       'actor', 'actors', 'actress', 'acts', 'actually', 'adam',
       'adamsandler', 'adaptation', 'addict', 'addiction', 'adopted',
       'adoption', 'adrienbrody', 'adult', 'adultery', 'adulthood',
       'adults', 'advantage', 'adventure', 'adventures', 'advertising',
       'advice', 'affair', 'affection', 'affections', 'afghanistan',
       'africa', 'african', 'aftercreditsstinger', 'afterlife', 'age',
       'aged', 'agedifference', 'agency', 'agenda', 'agent', 'agents',
       'aggressive',

In [10]:
import nltk

In [11]:
from nltk.stem.porter import PorterStemmer

In [12]:
ps=PorterStemmer()

In [13]:
def stem(text):
    L=[]
    for i in text.split():
        L.append(ps.stem(i))
        
    return " ".join(L)

In [14]:
stem(df["tags"][0])

'in the 22nd century, a parapleg marin is dispatch to the moon pandora on a uniqu mission, but becom torn between follow order and protect an alien civilization. action adventur fantasi sciencefict cultureclash futur spacewar spacecoloni societi spacetravel futurist romanc space alien tribe alienplanet cgi marin soldier battl loveaffair antiwar powerrel mindandsoul 3d samworthington zoesaldana sigourneyweav jame cameron'

In [15]:
df["tags"]=df["tags"].apply(stem)

In [16]:
df

movie_id                                     title  \
0        19995                                    Avatar   
1          285  Pirates of the Caribbean: At World's End   
2       206647                                   Spectre   
3        49026                     The Dark Knight Rises   
4        49529                               John Carter   
...        ...                                       ...   
4801      9367                               El Mariachi   
4802     72766                                 Newlyweds   
4803    231617                 Signed, Sealed, Delivered   
4804    126186                          Shanghai Calling   
4805     25975                         My Date with Drew   

                                                   tags  
0     in the 22nd century, a parapleg marin is dispa...  
1     captain barbossa, long believ to be dead, ha c...  
2     a cryptic messag from bond’ past send him on a...  
3     follow the death of district attorney harvey d...  
4     john carter is a war-weary, former militari ca...  
...                                                 ...  
4801  el mariachi just want to play hi guitar and ca...  
4802  a newlyw couple' honeymoon is upend by the arr...  
4803  "signed, sealed, delivered" introduc a dedic q...  
4804  when ambiti new york attorney sam is sent to s...  
4805  ever sinc the second grade when he first saw h...  

[4806 rows x 3 columns]

In [17]:
from sklearn.feature_extraction.text import CountVectorizer

In [18]:
cv=CountVectorizer(max_features=5000,stop_words="english")

In [19]:
vectors=cv.fit_transform(df["tags"]).toarray()

In [20]:
vectors[0]

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [21]:
from sklearn.metrics.pairwise import cosine_similarity

In [22]:
cosine_similarity(vectors)

array([[1.        , 0.08226127, 0.08471737, ..., 0.04456565, 0.        ,
        0.        ],
       [0.08226127, 1.        , 0.05884899, ..., 0.02321817, 0.        ,
        0.02465568],
       [0.08471737, 0.05884899, 1.        , ..., 0.0239114 , 0.0492366 ,
        0.        ],
       ...,
       [0.04456565, 0.02321817, 0.0239114 , ..., 1.        , 0.03885143,
        0.04007219],
       [0.        , 0.        , 0.0492366 , ..., 0.03885143, 1.        ,
        0.0825137 ],
       [0.        , 0.02465568, 0.        , ..., 0.04007219, 0.0825137 ,
        1.        ]])

In [23]:
cosine_similarity(vectors).shape

(4806, 4806)

In [24]:
similarity=cosine_similarity(vectors)

In [25]:
import pickle

In [26]:
with open("Similarity.pkl","wb") as file:
    pickle.dump(similarity,file)

In [27]:
similarity[0]

array([1.        , 0.08226127, 0.08471737, ..., 0.04456565, 0.        ,
       0.        ])

In [28]:
 # main function/

In [29]:
df

movie_id                                     title  \
0        19995                                    Avatar   
1          285  Pirates of the Caribbean: At World's End   
2       206647                                   Spectre   
3        49026                     The Dark Knight Rises   
4        49529                               John Carter   
...        ...                                       ...   
4801      9367                               El Mariachi   
4802     72766                                 Newlyweds   
4803    231617                 Signed, Sealed, Delivered   
4804    126186                          Shanghai Calling   
4805     25975                         My Date with Drew   

                                                   tags  
0     in the 22nd century, a parapleg marin is dispa...  
1     captain barbossa, long believ to be dead, ha c...  
2     a cryptic messag from bond’ past send him on a...  
3     follow the death of district attorney harvey d...  
4     john carter is a war-weary, former militari ca...  
...                                                 ...  
4801  el mariachi just want to play hi guitar and ca...  
4802  a newlyw couple' honeymoon is upend by the arr...  
4803  "signed, sealed, delivered" introduc a dedic q...  
4804  when ambiti new york attorney sam is sent to s...  
4805  ever sinc the second grade when he first saw h...  

[4806 rows x 3 columns]

In [30]:
sorted(list(enumerate(similarity[0])),reverse=True,key=lambda X :X[1])[1:6]

[(2405, 0.2901905000440047),
 (1214, 0.2847987184339659),
 (3728, 0.2605130246476754),
 (507, 0.253433161857307),
 (539, 0.2467838236981868)]

In [31]:
df[df["title"]=="Batman Begins"].index,df[df["title"]=="Batman Begins"].index[0]

(Index([119], dtype='int64'), 119)

In [32]:
distances=list(enumerate(similarity[0]))
distances

[(0, 1.0000000000000002),
 (1, 0.08226127456606226),
 (2, 0.08471737420873576),
 (3, 0.07300534327409847),
 (4, 0.1873171623163388),
 (5, 0.10838874619051501),
 (6, 0.03993615319154359),
 (7, 0.14673479641335554),
 (8, 0.0582716546748065),
 (9, 0.0967301666813349),
 (10, 0.101338918387628),
 (11, 0.11707322644771176),
 (12, 0.08885233166386385),
 (13, 0.04456565178215865),
 (14, 0.12824729401064427),
 (15, 0.06748819059987714),
 (16, 0.08000711205939975),
 (17, 0.1377056581888109),
 (18, 0.09493290614465533),
 (19, 0.08240856434303293),
 (20, 0.057807331301608),
 (21, 0.10814761408717502),
 (22, 0.06488856845230502),
 (23, 0.08603090020146065),
 (24, 0.052631578947368425),
 (25, 0.06802170238514359),
 (26, 0.152008377581442),
 (27, 0.18541926977182407),
 (28, 0.11470786693528087),
 (29, 0.06446025638903101),
 (30, 0.06622661785325219),
 (31, 0.15328483487124145),
 (32, 0.08447772061910234),
 (33, 0.09365858115816941),
 (34, 0.0),
 (35, 0.09733285267845754),
 (36, 0.1692777916923361),
 

In [33]:
m_list=sorted(distances,reverse=True,key=lambda x:x[1])[0:6]
m_list

[(0, 1.0000000000000002),
 (2405, 0.2901905000440047),
 (1214, 0.2847987184339659),
 (3728, 0.2605130246476754),
 (507, 0.253433161857307),
 (539, 0.2467838236981868)]

In [34]:
df.iloc[m_list[0][0]].title

'Avatar'

In [35]:
df.iloc[m_list[2][0]].title

'Aliens vs Predator: Requiem'

In [36]:
def recommend(movie):
    movie_index=df[df["title"]==movie].index[0]
    distances=list(enumerate(similarity[movie_index]))
    m_list=sorted(distances,reverse=True,key=lambda x:x[1])[0:10]
    
    for i in m_list:
        print(df.iloc[i[0]].title)

In [37]:
recommend("Avatar")

Avatar
Aliens
Aliens vs Predator: Requiem
Falcon Rising
Independence Day
Titan A.E.
Battle: Los Angeles
Meet Dave
Jupiter Ascending
Small Soldiers


In [38]:
recommend("Batman Begins")

Batman Begins
The Dark Knight
Batman
The Dark Knight Rises
Batman
10th & Wolf
Batman v Superman: Dawn of Justice
Rockaway
Defendor
Synecdoche, New York


In [39]:
import pickle

In [40]:
with open("movies.pkl","wb") as file:
    pickle.dump(df,file)

In [41]:
with open("movies.pkl","rb") as file:
    movies=pickle.load(file)

In [42]:
movies

movie_id                                     title  \
0        19995                                    Avatar   
1          285  Pirates of the Caribbean: At World's End   
2       206647                                   Spectre   
3        49026                     The Dark Knight Rises   
4        49529                               John Carter   
...        ...                                       ...   
4801      9367                               El Mariachi   
4802     72766                                 Newlyweds   
4803    231617                 Signed, Sealed, Delivered   
4804    126186                          Shanghai Calling   
4805     25975                         My Date with Drew   

                                                   tags  
0     in the 22nd century, a parapleg marin is dispa...  
1     captain barbossa, long believ to be dead, ha c...  
2     a cryptic messag from bond’ past send him on a...  
3     follow the death of district attorney harvey d...  
4     john carter is a war-weary, former militari ca...  
...                                                 ...  
4801  el mariachi just want to play hi guitar and ca...  
4802  a newlyw couple' honeymoon is upend by the arr...  
4803  "signed, sealed, delivered" introduc a dedic q...  
4804  when ambiti new york attorney sam is sent to s...  
4805  ever sinc the second grade when he first saw h...  

[4806 rows x 3 columns]

In [43]:
movies["title"]

0                                         Avatar
1       Pirates of the Caribbean: At World's End
2                                        Spectre
3                          The Dark Knight Rises
4                                    John Carter
                          ...                   
4801                                 El Mariachi
4802                                   Newlyweds
4803                   Signed, Sealed, Delivered
4804                            Shanghai Calling
4805                           My Date with Drew
Name: title, Length: 4806, dtype: object